### ISSUE TITLE
Possible inclusion in FlexibleAdapter

### ISSUE THREAD

**Issue by davideas** [ShamylZakariya/StickyHeaders#6]
Hello @ShamylZakariya,
I was wondering if your LayoutManager could be included (and adapted) in my [FlexibleAdapter](https://github.com/davideas/FlexibleAdapter) library. Currently, I use a different solution to make headers sticky and clickable(!), it works fair enough, but it has some bugs due to different internal state of the default LayoutManagers especially when removing items.
Basically, I searched a way, since long time now, to create a custom LayoutManager, but never had time to work on it.
Adaptation is necessary to cover:
- SmoothScroll for the expandable items.
- Identification of headers based on my implementation (probably I will change again).

Let me know. Thanks,
Davide

**Comment by ShamylZakariya** [comment]
@davideas I've just implemented scrollToPosition and smoothScrollToPosition, and am working on a performance fix for huge datasets. I'll be pushing an update this week with those fixes, and you're free to use it in any way you wish. If there's any specific functionality you'd like me to implement, such as clicking on headers let me know.

**Comment by davideas** [comment]
@ShamylZakariya, great!
Actually, I was able to resolve all the crashing issues, and now my Adapter is quite stable, but inclusion of your LayoutManager remains a long base task to do.

Indeed, the click on the sticky item is necessary otherwise the event is propagated to the view below.
When I will have more time I will focus on this inclusion.
It would be nice to have a differentiation of the 3 layout managers, Linear, Grid(extends linear) and Staggered.

Thanks!

**Comment by ShamylZakariya** [comment]
@davideas I've added collapsable sections, and while the (default) animation isn't *great*, the behavior is correct and reliable. I've also implemented `onSaveInstanceState` and `onRestoreInstanceState` to `StickyHeaderLayoutManager`.

I don't know if this is helpful, but thought you may be interested.

**Comment by davideas** [comment]
Hello @ShamylZakariya, I checked your latest changes, you are doing a good jobs, no dubts  :+1: 
Animation isn't great because you are using `notifyDataSetChanged()`!
Just keep in mind that now the custom Adapter you are making is not very usable, if not in the context of _sticky header_ / _sections_ only, and nothing else. Your Layout and Adapter are strictly related to each other's.

Now, you are on the point to do what I already did it, I mean: Click listeners, handling selection, keep selection on after expand / collapse, handling multiple items type, call notify on single item or a range of items (not `notifyDataSetChanged()`..), auto-expand, multiple layouts, etc (_the list is very long_)... Why?
In an App, any user cannot create selection mechanism and all those stuff every time for each Adapter from scratch, that's why I created _FlexibleAdapter_. The problem is that, there are a lot of libraries out there that make A-B-C things, and they are not compatible with others libraries that do C-D-E things, and you need all.
I hope you got the point :-)

**Comment by ShamylZakariya** [comment]
@davideas 

If you look at the implementation of `SectioningAdapter::setSectionIsCollapsed` here https://github.com/ShamylZakariya/StickyHeaders/blob/master/stickyheaders/src/main/java/org/zakariya/stickyheaders/SectioningAdapter.java#L400 you'll see that I'm actually just reloading the section data, not calling `notifyDataSetChanged`. And when I complain about the animation, it's only that the default animation is simple, but the thing does animate, I just don't feel like diving in any deeper.

Also, regarding the tight coupling between StickyHeaderLayoutManager and SectioningAdapter, it's fine by me. SectioningAdapter works *great* with other LayoutManagers, such as LinearLayoutManager. The only coupling is that StickyHeaderLayoutManager requires SectioningAdapter because, frankly, the StickyHeaderLayoutManager needs to know the sectioning structure of your data. AN alternative would be for users to have to provide *two* adapters, one vanilla adapter, and a second one which attempts to provide sectioning information using the data in the first adapter - that would be unintuitive.

Anyway, I guess I don't have anything I can contribute to your project. Feel free to use any code if you want, but it looks like you're making a very large, very powerful framework, and I'm making a tiny lib for a very specific purpose.
