### ISSUE TITLE
Scroll to position not working in your adapter.

### ISSUE THREAD

**Issue by yilzer** [ShamylZakariya/StickyHeaders#7]
When i want to scroll to a specific item in recyclerview with for example: mRecyclerview.scrollToPosition(20), the adapter list will not move, but start normally by the first item. 
It also happens when i call scroll to position from your StickyLayoutManager.

Is there an way i can fix this issue? 

Thanks in advance,

Yilzer

**Comment by ShamylZakariya** [comment]
After doing some research, it's clear that scrollToPosition is implemented in the LayoutManager, not RecyclerView. I'll get cracking on it, as well as smoothScrollToPosition.

**Comment by yilzer** [comment]
Thx for your response, 

When you're working on scrollToPosition it may also be important to save the scroll position in onsaveInstance. You can do this by calling:  currPosition = recyclerView.findFirstVisibleItemPosition();
The findFirstVisibleItemPosition() method is also an method in the linearlayout manager. I think it's important to have this part also in your stickylayout manager.

**Comment by ShamylZakariya** [comment]
yilzer,

I've implemented `scrollToPosition` and `smoothScrollToPosition` in the adapter, and they appear to work though I will be testing them further. That being said, I have a *serious* performance issue with HUGE datasets (hundreds of sections, thousands of items) which I want to tackle before I push an update to bintray. I expect to have that taken care of in a couple days, and I'll let you know and close this issue.

**Comment by ShamylZakariya** [comment]
https://github.com/ShamylZakariya/StickyHeaders/commit/37859b00c177bd8fcfa52534331185f0a2f067bd

I've also fixed a huge performance problem, so I'll be posting an update to bintray tonight, or so.

**Comment by yilzer** [comment]
Great work man, i've just two more questions for you:

- if i have 20 items with sticky header in my adapter, when i press on item 7 in grid. I want to show item 7 in adapter, but it shows item 3. Do you have an solution for this, so that it scrolls to the exact item.

- If i leave my activity or fragment i want to save the item that is visible right now, so i can scroll back in onsaveinstance how does this works in your layoutmanager? 

Thanks in advance!

**Comment by ShamylZakariya** [comment]
Yilzer

I'm implementing saved state for the StickyHeaderLayoutManager. It likely won't be completely automatic, though. You'll still need to explicitly pack and restore state in your activity's onSaveInstanceState, etc. See here: http://stackoverflow.com/questions/28236390/recyclerview-store-restore-state-between-activities -- I'll report when I've got this working.

Regarding your first point, about jumping to position, this is an interesting quandary. When you request smoothScrollToPosition or scrollToPosition, you're passing an adapter position, which **includes** headers (and "ghost headers", used internally by the library). This means that if you're looking at the first item of the first section, your adapter position would actually be 3.

I think your best bet there is to ask the adapter for the adapter position, e.g.:
``` (java)
showItem(int clickedIndex) {
    int section = ... // you need to determine which section you're dealing with
    int adapterPosition = adapter.getAdapterPositionForSectionItem(section, clickedIndex)
    recyclerView.scrollToPosition(adapterPosition)
}
```

**Comment by yilzer** [comment]
Thanks man! 

> int section = ... // you need to determine which section you're dealing with

How do i determine the section index? , because the only value that i have at that moment is the value that i want to show to the user in the adapter.

**Comment by ShamylZakariya** [comment]
First, I've implemented saved state and it appears to work.

https://github.com/ShamylZakariya/StickyHeaders/commit/dc63a98b8681f85b154c1d4875505aaac6b68826

Now, regarding your question, I guess I need to understand the problem. I'm parsing your usage as having one recyclerview -- and when users tap an item in it, the recycler scrolls that item to top of the viewport?

That being said, I've realized the fix is easier than I thoguht: as you have a reference to the ViewHolder, just use `RecyclerView.ViewHolder::getAdapterPosition()`.

**Comment by yilzer** [comment]
Great work man, I have an fragment with grid images , when the user taps on one of the images he goes to an new activity with your adapter (sticky layout manager). Inside this activity the images are displayed like an feed ( large images instagram style). So if the user taps on item 3 i want to show item 3 in feed with large images.

**Comment by ShamylZakariya** [comment]
So, if I understand correctly, what you have is a grid of items, indexed 0..N. Clicking on an item opens a list-like recyclerview detail using StickyHeaderLayoutManager where you have all those items, (0..N] but *each* is presented with its own header, where (presumably) the header is showing the item title/date/other-metadata. In your SectioningAdapter, each item gets its own section, with an associated header. So you have a list mapping like so:

```
[Header 0,(GhostHeader 0),Item 0],[Header 1,(Ghost Header 1), Item 1]...[Header N, (Ghost Header N),Item N]
```
(Ghost headers are created by the adapter as part of the layout process)

In this case, the need to multiply item index by 3 makes perfect sense. However: there's a semantically meaningful and forward-compatible way to handle this: instead of trying to scroll to the item, what you want is to scroll to the item's *header*. The header is indexed by section. So, here's what you will want to do:

```
void scrollToItem(int itemIndex) {
    int adapterPosition = adapter.getAdapterPositionForSectionHeader(itemIndex)
    recyclerView.scrollToPosition(adapterPosition);
}
```

**Comment by yilzer** [comment]
Great work again! This solved all my issues for now. This item can be closed!

**Comment by ShamylZakariya** [comment]
Fantastic, glad I could help.
